<a href="https://colab.research.google.com/github/LinaSachuk/The-Complete-Python-and-Machine-Learning-for-Financial-Analysis/blob/master/7_Python_101_Python_Libraries_for_Data_Analysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

my_list = [10, 20, 60, 70]

In [2]:
# Let's create a numpy array from the list "my_list"

my_list

[10, 20, 60, 70]

In [3]:
x= np.array(my_list)
print(type(x))
x

<class 'numpy.ndarray'>


array([10, 20, 60, 70])

In [4]:
# Multi-dimensional (Matrix definition) 

matrix = np.array([[5, 8], [7, 8]])
matrix

array([[5, 8],
       [7, 8]])

In [5]:
type(matrix)

numpy.ndarray

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [6]:
x = np.array([ [4,6,8,7], [20, 5, 6, 9]])
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [7]:
# "rand()" uniform distribution between 0 and 1

x = np.random.rand(15)
x

array([0.80756255, 0.57629978, 0.76242197, 0.69238991, 0.87024431,
       0.57536839, 0.94309555, 0.23416471, 0.03104774, 0.33471253,
       0.82528799, 0.57428339, 0.22101071, 0.39925552, 0.71535784])

In [8]:
# you can create a matrix of random number as well

x = np.random.rand(5, 5)
x

array([[0.34096105, 0.69935204, 0.28131607, 0.68286487, 0.39981899],
       [0.7628418 , 0.23190216, 0.37118792, 0.19684877, 0.92145123],
       [0.81880638, 0.44310089, 0.01641906, 0.3235538 , 0.88974055],
       [0.74880138, 0.22507469, 0.83310192, 0.38425239, 0.77834231],
       [0.7701258 , 0.98183866, 0.66471272, 0.11789264, 0.45932893]])

In [9]:
# "randn()" normal distribution between 0 and 1

x = np.random.randn(10)
x

array([ 0.44444627, -0.1548638 ,  0.43868325,  0.58547213, -0.46858357,
        1.81118788,  0.30019025, -1.31401707,  0.10270395, -0.82325701])

In [10]:
# "randint" is used to generate random integers between upper and lower bounds

x = np.random.randint(1, 10)
x

7

In [11]:
# "randint" can be used to generate a certain number of random itegers as follows

x = np.random.randint(1, 100, 15)
x

array([28,  1, 49,  7, 47, 20, 77, 26, 69, 10, 21, 32, 42, 58, 94])

In [12]:
# np.arange creates an evenly spaced values within a given interval

x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
# Create an evenly spaced values with a step of 5

x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [14]:
# create a diagonal of ones and zeros everywhere else

x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [15]:
# Array of ones

x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# Matrices of ones

x = np.ones((10, 10))
x


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
# Array of zeros

x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [18]:
x = int(input("Enter a number :"))
x = np.random.randint(1, x , 20)
x

Enter a number :7


array([2, 2, 4, 1, 3, 1, 1, 6, 1, 4, 4, 5, 5, 4, 2, 2, 1, 6, 5, 3])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [19]:
# Let's define a one-dimensional array 

my_list = [-30, 4, 50, 60, 29, 22, 90, 87]
my_list
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  22,  90,  87])

In [20]:
# Get Length of a numpy array

len(x)

8

In [21]:
# Get shape

x.shape

(8,)

In [22]:
# Obtain the datatype

type(x)

numpy.ndarray

In [23]:
# Reshape 1D array into a matrix

z = x.reshape(2,4)
z

array([[-30,   4,  50,  60],
       [ 29,  22,  90,  87]])

In [24]:
# Obtain the maximum element (value)

x.max()

90

In [25]:
# Obtain the minimum element (value)

x.min()

-30

In [26]:
# Obtain the location of the max element

x.argmax()

6

In [27]:
# Obtain the location of the min element

x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [28]:
x = np.arange(300, 500, 10)
x

array([300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420,
       430, 440, 450, 460, 470, 480, 490])

In [29]:
z = x.reshape(4,5)
z

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [30]:
x = np.random.randint(-1000, 1000, (20,20))
x

array([[-962,  270, -824, -328, -131,  933, -940, -315,  538, -779,  588,
        -692, -779,  135, -921,  694,  611,  647, -220,  145],
       [-336,  124,  540,  707,  -25,   70, -520, -795, -226, -168, -598,
        -105, -567, -173,  427,  922,   17, -682,  432,  -22],
       [ 768, -751,  931, -378,  960,  892, -269,  901, -966,  237,   55,
        -147,  566, -925,  271,   95, -417,  988,  181, -965],
       [ 345, -978,  852, -667,  868,  322, -634,  400,  512,  786,  469,
         529,  233, -177,  710,  883,  429, -519,  294,  694],
       [ 680,  615,  -84, -351, -538, -453, -774, -412,   11, -413, -868,
        -366,  627, -435, -951, -216, -425, -675, -297, -608],
       [  34,  943,  457,  872,  551,  970, -823, -644, -344,  392,  952,
         283,  608, -376,  475,  812, -286,  803,  673,  279],
       [-349,  -13, -986, -969, -526,  720,  744,  169,  -76, -444,  241,
        -464, -750,  684, -939, -736,  576, -802,  562, -354],
       [-825, -967, -254, -297,  716,  38

In [31]:
x.shape

(20, 20)

In [32]:
x.max()

992

In [33]:
x.min()

-986

In [34]:
x.mean()

2.8175

In [35]:
print(f'The maximum value is: {x.max()} and the minimum value is: {x.min()}')

The maximum value is: 992 and the minimum value is: -986


# 4. MATHEMATICAL OPERATIONS

In [55]:
# np.arange() returns an evenly spaced values within a given interval

x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# Add 2 numpy arrays together

sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

# 5. SLICING AND INDEXING 

In [38]:
# Access specific index from the numpy array


In [39]:
# Starting from the first index 0 up until and NOT inlcluding the last element


In [40]:
# Broadcasting, altering several values in a numpy array at once


In [41]:
# Let's define a two dimensional numpy array


In [42]:
# Get a row from a mtrix


In [43]:
# Get one element


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [44]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [45]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

Please enter a positive integer value: 8


array([3, 2, 2, 5, 1, 4, 3, 4, 7, 1, 1, 4, 5, 5, 1, 5, 1, 5, 7, 1])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [46]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [47]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [48]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[ 286 -654  901 -887 -481  790 -372  546 -744  225  -90  949  585 -192
   141 -649 -287 -413  619  468]
 [-607 -217  837  815 -513  998 -938  442 -821  784 -780  246  420 -865
  -479  799  435   92  142  340]
 [ -47  -69 -161  775 -498 -966  440  263  330  491 -925 -802  414  471
   922 -929 -847 -773 -496  686]
 [ 656 -655 -802  910 -641  205 -757 -807 -554  150  123 -345  108  809
   537 -865 -289  837 -999 -168]
 [ 587 -298 -425 -952  786  -37  725  361  196  871  693  314  643 -903
   632 -255 -481  -59 -210 -871]
 [-630  176 -827  276  661 -347  474 -300  414  710 -544 -142 -589   81
  -300  358  385 -998  663 -466]
 [ 437 -151 -334 -372  -99  -48  754  453 -467  542  -54  430  213  383
   850 -541  -63  691  810 -317]
 [-910 -830 -655  994  266  362 -735 -582 -572   87 -876  887  570 -906
  -904  165 -270 -628 -274  344]
 [ 187  375  143  361  394  818  615 -165  598  778  250 -274  263  284
  -995  275  907 -808 -999 -628]
 [ 549 -857 -106   79  983 -515 -553 -808 -204 -600 -84

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [49]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [50]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [51]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [52]:
X[:2, 3:]  = X[:2, 3:] * 2

In [53]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [54]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])