<a href="https://colab.research.google.com/github/LinaSachuk/The-Complete-Python-and-Machine-Learning-for-Financial-Analysis/blob/master/7_Python_101_Python_Libraries_for_Data_Analysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

my_list = [10, 20, 60, 70]

In [3]:
# Let's create a numpy array from the list "my_list"

my_list

[10, 20, 60, 70]

In [4]:
x= np.array(my_list)
print(type(x))
x

<class 'numpy.ndarray'>


array([10, 20, 60, 70])

In [5]:
# Multi-dimensional (Matrix definition) 

matrix = np.array([[5, 8], [7, 8]])
matrix

array([[5, 8],
       [7, 8]])

In [6]:
type(matrix)

numpy.ndarray

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [7]:
x = np.array([ [4,6,8,7], [20, 5, 6, 9]])
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [8]:
# "rand()" uniform distribution between 0 and 1

x = np.random.rand(15)
x

array([0.66886006, 0.05975676, 0.33005412, 0.19208567, 0.41822697,
       0.67967629, 0.41763428, 0.24620088, 0.30283854, 0.90117296,
       0.06706182, 0.37632639, 0.64286532, 0.74120022, 0.298033  ])

In [9]:
# you can create a matrix of random number as well

x = np.random.rand(5, 5)
x

array([[0.05535438, 0.21784617, 0.97297015, 0.624275  , 0.02735048],
       [0.41221063, 0.32671931, 0.73017759, 0.92794381, 0.89599349],
       [0.97697253, 0.54699543, 0.9853166 , 0.83163719, 0.18479151],
       [0.61054373, 0.88382035, 0.78570644, 0.75685804, 0.42148574],
       [0.26060587, 0.28730058, 0.96308595, 0.017579  , 0.333431  ]])

In [10]:
# "randn()" normal distribution between 0 and 1

x = np.random.randn(10)
x

array([-1.59329485,  1.1134525 ,  0.21301715,  0.05149756, -2.16155476,
        0.23663312, -0.22827249, -2.28350534,  0.24027819, -0.02497238])

In [11]:
# "randint" is used to generate random integers between upper and lower bounds

x = np.random.randint(1, 10)
x

1

In [12]:
# "randint" can be used to generate a certain number of random itegers as follows

x = np.random.randint(1, 100, 15)
x

array([45, 91, 10,  4,  2, 36, 68, 79, 27, 81, 87, 36, 83, 78, 99])

In [13]:
# np.arange creates an evenly spaced values within a given interval

x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
# Create an evenly spaced values with a step of 5

x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [15]:
# create a diagonal of ones and zeros everywhere else

x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [16]:
# Array of ones

x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# Matrices of ones

x = np.ones((10, 10))
x


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
# Array of zeros

x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [20]:
x = int(input("Enter a number :"))
x = np.random.randint(1, x , 20)
x

Enter a number :8


array([5, 4, 6, 7, 5, 2, 4, 1, 6, 4, 5, 5, 5, 6, 3, 1, 7, 2, 4, 6])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [22]:
# Let's define a one-dimensional array 

my_list = [-30, 4, 50, 60, 29, 22, 90, 87]
my_list
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  22,  90,  87])

In [21]:
# Get Length of a numpy array

len(x)

20

In [23]:
# Get shape

x.shape

(8,)

In [24]:
# Obtain the datatype

type(x)

numpy.ndarray

In [25]:
# Reshape 1D array into a matrix

z = x.reshape(2,4)
z

array([[-30,   4,  50,  60],
       [ 29,  22,  90,  87]])

In [26]:
# Obtain the maximum element (value)

x.max()

90

In [27]:
# Obtain the minimum element (value)

x.min()

-30

In [28]:
# Obtain the location of the max element

x.argmax()

6

In [29]:
# Obtain the location of the min element

x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

# 4. MATHEMATICAL OPERATIONS

In [ ]:
# np.arange() returns an evenly spaced values within a given interval


In [ ]:
# Add 2 numpy arrays together


**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

# 5. SLICING AND INDEXING 

In [ ]:
# Access specific index from the numpy array


In [ ]:
# Starting from the first index 0 up until and NOT inlcluding the last element


In [ ]:
# Broadcasting, altering several values in a numpy array at once


In [ ]:
# Let's define a two dimensional numpy array


In [ ]:
# Get a row from a mtrix


In [ ]:
# Get one element


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X