<a href="https://colab.research.google.com/github/LinaSachuk/The-Complete-Python-and-Machine-Learning-for-Financial-Analysis/blob/master/7_Python_101_Python_Libraries_for_Data_Analysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

my_list = [10, 20, 60, 70]

In [3]:
# Let's create a numpy array from the list "my_list"

my_list

[10, 20, 60, 70]

In [4]:
x= np.array(my_list)
print(type(x))
x

<class 'numpy.ndarray'>


array([10, 20, 60, 70])

In [5]:
# Multi-dimensional (Matrix definition) 

matrix = np.array([[5, 8], [7, 8]])
matrix

array([[5, 8],
       [7, 8]])

In [6]:
type(matrix)

numpy.ndarray

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [7]:
x = np.array([ [4,6,8,7], [20, 5, 6, 9]])
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [8]:
# "rand()" uniform distribution between 0 and 1

x = np.random.rand(15)
x

array([0.05463976, 0.74502124, 0.70086427, 0.84675612, 0.16360929,
       0.27113535, 0.46855266, 0.67536638, 0.13231754, 0.39206087,
       0.71847815, 0.87195747, 0.73710856, 0.83882576, 0.15378652])

In [47]:
# you can create a matrix of random number as well

x = np.random.rand(5, 5)
x

array([[0.27061221, 0.28400587, 0.14776248, 0.87911042, 0.32435391],
       [0.15071183, 0.0929809 , 0.70485023, 0.13221497, 0.3304109 ],
       [0.40141841, 0.89450646, 0.41483328, 0.89297461, 0.68026142],
       [0.69067174, 0.10108451, 0.51844917, 0.51256831, 0.7640082 ],
       [0.79185873, 0.59986762, 0.38236508, 0.34034743, 0.75613599]])

In [48]:
# "randn()" normal distribution between 0 and 1

x = np.random.randn(10)
x

array([-0.06958811,  0.55457184, -0.34832079,  0.08236816, -1.11912123,
       -0.99934937, -1.38568916,  1.02486452, -0.28058014,  2.20587888])

In [49]:
# "randint" is used to generate random integers between upper and lower bounds

x = np.random.randint(1, 10)
x

6

In [50]:
# "randint" can be used to generate a certain number of random itegers as follows

x = np.random.randint(1, 100, 15)
x

array([99, 73, 76, 27, 29, 66, 51, 72, 23, 82, 74, 50, 11, 73, 48])

In [51]:
# np.arange creates an evenly spaced values within a given interval

x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
# Create an evenly spaced values with a step of 5

x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [53]:
# create a diagonal of ones and zeros everywhere else

x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [54]:
# Array of ones

x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
# Matrices of ones

x = np.ones((10, 10))
x


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
# Array of zeros

x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [63]:
x = int(input("Enter a number :"))
x = np.random.randint(1, x , 20)
x

Enter a number :8


array([7, 2, 3, 1, 7, 5, 1, 4, 1, 5, 5, 3, 1, 5, 7, 5, 3, 3, 3, 7])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [19]:
# Let's define a one-dimensional array 



In [20]:
# Get Length of a numpy array


In [21]:
# Get shape


In [22]:
# Obtain the datatype


In [23]:
# Reshape 1D array into a matrix


In [24]:
# Obtain the maximum element (value)


In [25]:
# Obtain the minimum element (value)


In [26]:
# Obtain the location of the max element


In [27]:
# Obtain the location of the min element


**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

# 4. MATHEMATICAL OPERATIONS

In [28]:
# np.arange() returns an evenly spaced values within a given interval


In [29]:
# Add 2 numpy arrays together


**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

# 5. SLICING AND INDEXING 

In [30]:
# Access specific index from the numpy array


In [31]:
# Starting from the first index 0 up until and NOT inlcluding the last element


In [32]:
# Broadcasting, altering several values in a numpy array at once


In [33]:
# Let's define a two dimensional numpy array


In [34]:
# Get a row from a mtrix


In [35]:
# Get one element


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [36]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [37]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

Please enter a positive integer value: 34


array([30, 21, 32, 19, 32,  4, 32, 19, 13,  8,  5, 24, 15,  9, 11,  7,  5,
        4,  6, 20])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [38]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [39]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [40]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[ -43  901 -813  498 -874 -701 -941 -220 -202  267 -226 -812 -420   45
  -938  149  883  845  964  377]
 [ 918  734  796 -464 -325 -912 -129 -905  364   83  -83   54  785  627
  -331  858  738  767  -13 -784]
 [ 285 -173  164  486 -842 -179 -612  684   19 -781  529 -681 -572  -76
   980  360 -746  748  335  206]
 [-576 -214  859 -746 -704 -942 -947 -938  656 -563 -974  599  194  555
   850 -450  796 -473 -567 -243]
 [  -5  112  837  853 -553 -976 -139 -553 -497  414 -263 -852  518  921
  -105  168 -992 -910  421  817]
 [ 751  242  645 -849  -79 -450  -53  435    3   91  -99 -588 -863  360
   -48 -681 -268  679  557   54]
 [-893  425 -223 -550  552  753  422  536  881  997  144  560  -65  -71
  -300  888  616  726  585  797]
 [ 186  936 -295  794  125  380 -815 -437  -66  826  859  574  767 -982
  -571  216 -363 -610 -779 -845]
 [ 841  577  759   28  158  540 -363 -429 -693  962 -803 -598 -196  296
   381   81 -794 -287  847 -690]
 [ 176  317  326 -227  215  131  756  767   38  650  -5

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [41]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [42]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [43]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [44]:
X[:2, 3:]  = X[:2, 3:] * 2

In [45]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [46]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])