<a href="https://colab.research.google.com/github/LinaSachuk/The-Complete-Python-and-Machine-Learning-for-Financial-Analysis/blob/master/7_Python_101_Python_Libraries_for_Data_Analysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

my_list = [10, 20, 60, 70]

In [3]:
# Let's create a numpy array from the list "my_list"

my_list

[10, 20, 60, 70]

In [7]:
x= np.array(my_list)
print(type(x))
x

<class 'numpy.ndarray'>


array([10, 20, 60, 70])

In [13]:
# Multi-dimensional (Matrix definition) 

matrix = np.array([[5, 8], [7, 8]])
matrix

array([[5, 8],
       [7, 8]])

In [14]:
type(matrix)

numpy.ndarray

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [16]:
x = np.array([ [4,6,8,7], [20, 5, 6, 9]])
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [ ]:
# "rand()" uniform distribution between 0 and 1


In [ ]:
# you can create a matrix of random number as well


In [ ]:
# "randn()" normal distribution between 0 and 1


In [ ]:
# "randint" is used to generate random integers between upper and lower bounds


In [ ]:
# "randint" can be used to generate a certain number of random itegers as follows


In [ ]:
# np.arange creates an evenly spaced values within a given interval


In [ ]:
# Create an evenly spaced values with a step of 5


In [ ]:
# create a diagonal of ones and zeros everywhere else


In [ ]:
# Array of ones


In [ ]:
# Matrices of ones


In [ ]:
# Array of zeros


**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [ ]:
# Let's define a one-dimensional array 


In [ ]:
# Get Length of a numpy array


In [ ]:
# Get shape


In [ ]:
# Obtain the datatype


In [ ]:
# Reshape 1D array into a matrix


In [ ]:
# Obtain the maximum element (value)


In [ ]:
# Obtain the minimum element (value)


In [ ]:
# Obtain the location of the max element


In [ ]:
# Obtain the location of the min element


**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

# 4. MATHEMATICAL OPERATIONS

In [ ]:
# np.arange() returns an evenly spaced values within a given interval


In [ ]:
# Add 2 numpy arrays together


**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

# 5. SLICING AND INDEXING 

In [ ]:
# Access specific index from the numpy array


In [ ]:
# Starting from the first index 0 up until and NOT inlcluding the last element


In [ ]:
# Broadcasting, altering several values in a numpy array at once


In [ ]:
# Let's define a two dimensional numpy array


In [ ]:
# Get a row from a mtrix


In [ ]:
# Get one element


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X