<a href="https://colab.research.google.com/github/LinaSachuk/The-Complete-Python-and-Machine-Learning-for-Financial-Analysis/blob/master/7_Python_101_Python_Libraries_for_Data_Analysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

my_list = [10, 20, 60, 70]

In [3]:
# Let's create a numpy array from the list "my_list"

my_list

[10, 20, 60, 70]

In [4]:
x= np.array(my_list)
print(type(x))
x

<class 'numpy.ndarray'>


array([10, 20, 60, 70])

In [5]:
# Multi-dimensional (Matrix definition) 

matrix = np.array([[5, 8], [7, 8]])
matrix

array([[5, 8],
       [7, 8]])

In [6]:
type(matrix)

numpy.ndarray

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [7]:
x = np.array([ [4,6,8,7], [20, 5, 6, 9]])
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [8]:
# "rand()" uniform distribution between 0 and 1

x = np.random.rand(15)
x

array([0.457504  , 0.80584431, 0.91479578, 0.48244235, 0.91047351,
       0.65039531, 0.08611376, 0.40149747, 0.33297448, 0.37147813,
       0.25158627, 0.33700392, 0.2387526 , 0.94295027, 0.80996889])

In [9]:
# you can create a matrix of random number as well

x = np.random.rand(5, 5)
x

array([[0.45932822, 0.39060317, 0.70360694, 0.34572452, 0.18397381],
       [0.65471224, 0.54509984, 0.98715507, 0.61883348, 0.34360078],
       [0.96829702, 0.12105035, 0.51541906, 0.38707508, 0.08139964],
       [0.33707438, 0.45727356, 0.01364267, 0.03942814, 0.35205193],
       [0.37591483, 0.79279799, 0.82834808, 0.41618029, 0.31233502]])

In [10]:
# "randn()" normal distribution between 0 and 1

x = np.random.randn(10)
x

array([ 1.14002116, -0.9000054 ,  0.32439866,  1.35186588, -0.41529884,
       -0.94288497,  1.11831418,  1.44506115, -0.92433995, -0.52382173])

In [11]:
# "randint" is used to generate random integers between upper and lower bounds

x = np.random.randint(1, 10)
x

6

In [12]:
# "randint" can be used to generate a certain number of random itegers as follows

x = np.random.randint(1, 100, 15)
x

array([ 2, 45, 56, 52, 56,  2, 94, 28, 41, 99, 88, 56, 27, 14, 21])

In [13]:
# np.arange creates an evenly spaced values within a given interval

x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
# Create an evenly spaced values with a step of 5

x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [15]:
# create a diagonal of ones and zeros everywhere else

x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [16]:
# Array of ones

x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# Matrices of ones

x = np.ones((10, 10))
x


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
# Array of zeros

x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [19]:
x = int(input("Enter a number :"))
x = np.random.randint(1, x , 20)
x

Enter a number :4


array([1, 1, 3, 1, 2, 2, 3, 1, 3, 1, 1, 2, 3, 3, 3, 2, 2, 3, 1, 2])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [20]:
# Let's define a one-dimensional array 

my_list = [-30, 4, 50, 60, 29, 22, 90, 87]
my_list
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  22,  90,  87])

In [21]:
# Get Length of a numpy array

len(x)

8

In [22]:
# Get shape

x.shape

(8,)

In [23]:
# Obtain the datatype

type(x)

numpy.ndarray

In [24]:
# Reshape 1D array into a matrix

z = x.reshape(2,4)
z

array([[-30,   4,  50,  60],
       [ 29,  22,  90,  87]])

In [25]:
# Obtain the maximum element (value)

x.max()

90

In [26]:
# Obtain the minimum element (value)

x.min()

-30

In [27]:
# Obtain the location of the max element

x.argmax()

6

In [28]:
# Obtain the location of the min element

x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [29]:
x = np.arange(300, 500, 10)
x

array([300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420,
       430, 440, 450, 460, 470, 480, 490])

In [30]:
z = x.reshape(4,5)
z

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [31]:
x = np.random.randint(-1000, 1000, (20,20))
x

array([[ -76, -327,  832,  400, -633, -224, -927,  936, -875, -562, -253,
        -206,  963,  491,  371,  340, -727, -127, -724,  733],
       [-976,  396,  488, -919,  666,  141,  -34, -288, -394,  527, -823,
        -474,  831,  581,  543, -708, -332,  469,   87,  129],
       [-110, -367, -644,   80, -172, -157,  736, -664, -777, -684, -974,
        -997, -123, -993, -481,   98,   68,  222,   98, -182],
       [ 679,   47,  943, -348,  130,  180, -896,   62, -333,  133, -992,
        -778,  549,  308, -405, -429,  576,  159,  252,  663],
       [-612,   42, -685, -310, -571, -111, -452, -859,  603,  309,  562,
         490,  138, -600, -986, -953,  586, -689,  451,  -17],
       [-642, -165,  279, -875,  965,  778,  612, -342, -699,  -18,  136,
         374,  712, -923,  764,  404,  182, -309,  404,  285],
       [ 510, -297,  452, -751, -647,   19, -211,   37, -990,  203,  424,
        -125,  694,  344,  234,  983,  666, -229,  701, -577],
       [ 406,  273, -270, -187,  922,  15

In [32]:
x.shape

(20, 20)

In [33]:
x.max()

994

In [34]:
x.min()

-998

In [35]:
x.mean()

-11.2825

In [36]:
print(f'The maximum value is: {x.max()} and the minimum value is: {x.min()}')

The maximum value is: 994 and the minimum value is: -998


# 4. MATHEMATICAL OPERATIONS

In [37]:
# np.arange() returns an evenly spaced values within a given interval

x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# Add 2 numpy arrays together

sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [42]:
sqrt = np.sqrt(squared)
sqrt


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [44]:
X = [3, 20, 30]
Y = [4, 6, 7]

X = np.array(X)
Y = np.array(Y)
Z = np.sqrt((X**2 + Y**2))
Z

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [45]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [46]:
# Access specific index from the numpy array

x[0]

20

In [48]:
# Starting from the first index 0 up until and NOT inlcluding the last element

x[0:3]

array([20, 40, 50])

In [49]:
# Broadcasting, altering several values in a numpy array at once

x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [50]:
# Let's define a two dimensional numpy array

matrix = np.random.randint(1, 10, (5,5))
matrix

array([[6, 8, 8, 6, 8],
       [4, 9, 7, 1, 2],
       [8, 2, 2, 7, 2],
       [4, 7, 2, 4, 6],
       [9, 6, 9, 2, 3]])

In [51]:
# Get a row from a mtrix

matrix[2]

array([8, 2, 2, 7, 2])

In [52]:
# Get one element

matrix[0][2]

8

In [53]:
mini_matrix = matrix[:3]
mini_matrix

array([[6, 8, 8, 6, 8],
       [4, 9, 7, 1, 2],
       [8, 2, 2, 7, 2]])

In [54]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[8, 6, 8],
       [7, 1, 2],
       [2, 7, 2],
       [2, 4, 6],
       [9, 2, 3]])

In [55]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[6, 8],
       [4, 9],
       [8, 2],
       [4, 7],
       [9, 6]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [70]:
X = np.array([[2, 30, 20 ,-2 ,-4],
                  [3, 4,  40, -3, -2],
                  [-3, 4, -6, 90, 10],
                  [25, 45, 34, 22, 12],
                  [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [71]:
X[4]=-1
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [72]:
X[:2, 3:] = X[:2, 3:] * 2
X 

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

# 6. ELEMENTS SELECTION (CONDITIONAL)

In [73]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[9, 8, 8, 8, 4],
       [6, 2, 6, 5, 9],
       [3, 6, 4, 9, 5],
       [4, 7, 5, 9, 4],
       [7, 3, 6, 8, 9]])

In [74]:
new_matrix = matrix[matrix>3]
new_matrix

array([9, 8, 8, 8, 4, 6, 6, 5, 9, 6, 4, 9, 5, 4, 7, 5, 9, 4, 7, 6, 8, 9])

In [75]:
new_matrix = matrix[matrix%2 ==0]
new_matrix

array([8, 8, 8, 4, 6, 2, 6, 6, 4, 4, 4, 6, 8])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [78]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [79]:
X[X<0]=0
X

array([[ 2, 30, 20,  0,  0],
       [ 3,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [80]:
X[X%2==1]=25
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X